version: '3'

networks:
  backend:
    external: true

services:
  redis-master:
    container_name: "redis-master-1"
    image: redis
    ports:
      - "6379:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./redis-master-1/data-master-1:/data/"
      - "./redis-master-1/master-1.conf:/etc/redis.conf"
    networks:
      - backend

  redis-slave-1:
    container_name: "redis-slave-1"
    image: redis
    ports:
      - "6380:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./redis-slave-1/data-slave-1:/data/"
      - "./redis-slave-1/slave-1.conf:/etc/redis.conf"
    networks:
      - backend

  redis-slave-2:
    container_name: "redis-slave-2"
    image: redis
    ports:
      - "6381:6379"
    command: "redis-server /etc/redis.conf"
    volumes:
      - "./redis-slave-2/data-slave-2:/data/"
      - "./redis-slave-2/slave-2.conf:/etc/redis.conf"
    networks:
      - backend


